name: 'Sign'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Switch branch
        run: |
          git config user.name JC5
          git config user.email release@firefly-iii.org
          git pull

          # do some configuration
          sudo timedatectl set-timezone Europe/Amsterdam
          git config advice.addIgnoredFile false
          git config push.autoSetupRemote true

          # create new release branches
          BRANCHNAME=release-$(date +'%s')
          git checkout -b $BRANCHNAME

          echo $(date) > file.txt

          # add all content, except output.txt (this contains the changelog and/or the download instructions)
          echo 'Add all and reset output.txt'
          git add -A
          git commit -S -m "Auto commit for release ABC on $(date +'%Y-%m-%d')" || true
          git push

          # create PR
          gh pr create -B main -H $BRANCHNAME --title 'Release thing test' --body 'Created by Github action'
          gh pr merge -b 'Auto merge bla bla' -d --rebase
          
          # checkout develop again, and pull it.
          
          # checkout develop and track it from origin
          git checkout develop
          git pull
          git tag -a $BRANCHNAME -m "Development release ABC on $(date +'%Y-%m-%d')"
          git push
    env:
      GH_TOKEN: ${{ github.token }}
