name: 'Sign'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Switch branch
        run: |
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git pull

          # do some configuration
          sudo timedatectl set-timezone Europe/Amsterdam
          git config advice.addIgnoredFile false
          git config push.autoSetupRemote true

          # create new release branches
          BRANCHNAME=release-$(date +'%s')
          git checkout -b $BRANCHNAME

          
          echo $(date) > file.txt

          # add all content, except output.txt (this contains the changelog and/or the download instructions)
          echo 'Add all and reset output.txt'
          git add -A
          git commit -m "Auto commit for release '$version' on $(date +'%Y-%m-%d')" || true
          git push

          # create PR
          gh pr create -B main -H $BRANCHNAME --title 'Release thing test' --body 'Created by Github action'
          gh pr merge -b 'Auto merge bla bla' -d --rebase
    env:
      GH_TOKEN: ${{ github.token }}